/**
 * Core Domain Constants & Configuration
 * D5 IPL Fantasy Platform
 */

export const IPL_TEAMS = {
  MI:   { name: "Mumbai Indians", color: "#004BA0", short: "MI", city: "Mumbai", titleWins: 5 },
  CSK:  { name: "Chennai Super Kings", color: "#F5A623", short: "CSK", city: "Chennai", titleWins: 5 },
  RCB:  { name: "Royal Challengers Bengaluru", color: "#EC1C24", short: "RCB", city: "Bengaluru", titleWins: 0 },
  KKR:  { name: "Kolkata Knight Riders", color: "#3B1B6B", short: "KKR", city: "Kolkata", titleWins: 3 },
  DC:   { name: "Delhi Capitals", color: "#00AAE4", short: "DC", city: "Delhi", titleWins: 0 },
  SRH:  { name: "Sunrisers Hyderabad", color: "#FF6B00", short: "SRH", city: "Hyderabad", titleWins: 2 },
  PBKS: { name: "Punjab Kings", color: "#ED1B24", short: "PBKS", city: "Mohali", titleWins: 0 },
  RR:   { name: "Rajasthan Royals", color: "#EA1A85", short: "RR", city: "Jaipur", titleWins: 1 },
  LSG:  { name: "Lucknow Super Giants", color: "#00B4D8", short: "LSG", city: "Lucknow", titleWins: 0 },
  GT:   { name: "Gujarat Titans", color: "#1C4B8E", short: "GT", city: "Ahmedabad", titleWins: 1 },
};

export const IPL_SCHEDULE = [
  { id: "m1",  date: "2026-03-28", time: "7:30 PM", team1: "CSK", team2: "RCB", venue: "MA Chidambaram Stadium, Chennai" },
  { id: "m2",  date: "2026-03-29", time: "3:30 PM", team1: "KKR", team2: "SRH", venue: "Eden Gardens, Kolkata" },
  { id: "m3",  date: "2026-03-29", time: "7:30 PM", team1: "RR",  team2: "LSG", venue: "Sawai Mansingh Stadium, Jaipur" },
  { id: "m4",  date: "2026-03-30", time: "7:30 PM", team1: "GT",  team2: "MI",  venue: "Narendra Modi Stadium, Ahmedabad" },
  { id: "m5",  date: "2026-03-31", time: "7:30 PM", team1: "PBKS",team2: "DC",  venue: "PCA Stadium, Mullanpur" },
  { id: "m6",  date: "2026-04-01", time: "7:30 PM", team1: "RCB", team2: "KKR", venue: "M. Chinnaswamy Stadium, Bengaluru" },
  { id: "m7",  date: "2026-04-02", time: "7:30 PM", team1: "SRH", team2: "CSK", venue: "Rajiv Gandhi Stadium, Hyderabad" },
  { id: "m8",  date: "2026-04-03", time: "7:30 PM", team1: "LSG", team2: "GT",  venue: "Ekana Stadium, Lucknow" },
  { id: "m9",  date: "2026-04-04", time: "3:30 PM", team1: "MI",  team2: "RR",  venue: "Wankhede Stadium, Mumbai" },
  { id: "m10", date: "2026-04-04", time: "7:30 PM", team1: "DC",  team2: "CSK", venue: "Arun Jaitley Stadium, Delhi" },
  { id: "m11", date: "2026-04-05", time: "3:30 PM", team1: "PBKS",team2: "RCB", venue: "PCA Stadium, Mullanpur" },
  { id: "m12", date: "2026-04-05", time: "7:30 PM", team1: "KKR", team2: "GT",  venue: "Eden Gardens, Kolkata" },
  { id: "m13", date: "2026-04-06", time: "7:30 PM", team1: "SRH", team2: "RR",  venue: "Rajiv Gandhi Stadium, Hyderabad" },
  { id: "m14", date: "2026-04-07", time: "7:30 PM", team1: "CSK", team2: "MI",  venue: "MA Chidambaram Stadium, Chennai" },
  { id: "m15", date: "2026-04-08", time: "7:30 PM", team1: "DC",  team2: "LSG", venue: "Arun Jaitley Stadium, Delhi" },
  { id: "m16", date: "2026-04-09", time: "7:30 PM", team1: "GT",  team2: "PBKS",venue: "Narendra Modi Stadium, Ahmedabad" },
  { id: "m17", date: "2026-04-10", time: "7:30 PM", team1: "RCB", team2: "SRH", venue: "M. Chinnaswamy Stadium, Bengaluru" },
  { id: "m18", date: "2026-04-11", time: "7:30 PM", team1: "MI",  team2: "DC",  venue: "Wankhede Stadium, Mumbai" },
  { id: "m19", date: "2026-04-12", time: "3:30 PM", team1: "RR",  team2: "KKR", venue: "Sawai Mansingh Stadium, Jaipur" },
  { id: "m20", date: "2026-04-12", time: "7:30 PM", team1: "LSG", team2: "GT",  venue: "Ekana Stadium, Lucknow" },
];

export const IPL_SQUADS = {
  MI: [
    { name: "Rohit Sharma", role: "BAT", overseas: false },
    { name: "Jasprit Bumrah", role: "BOWL", overseas: false },
    { name: "Suryakumar Yadav", role: "BAT", overseas: false },
    { name: "Hardik Pandya", role: "ALL", overseas: false },
    { name: "Tilak Varma", role: "BAT", overseas: false },
    { name: "Tim David", role: "BAT", overseas: true },
    { name: "Ryan Rickelton", role: "WK", overseas: true },
    { name: "Trent Boult", role: "BOWL", overseas: true },
    { name: "Will Jacks", role: "ALL", overseas: true },
    { name: "Deepak Chahar", role: "BOWL", overseas: false },
    { name: "Mitchell Santner", role: "ALL", overseas: true },
    { name: "Karn Sharma", role: "BOWL", overseas: false },
  ],
  CSK: [
    { name: "Ruturaj Gaikwad", role: "BAT", overseas: false },
    { name: "MS Dhoni", role: "WK", overseas: false },
    { name: "Ravindra Jadeja", role: "ALL", overseas: false },
    { name: "Shivam Dube", role: "ALL", overseas: false },
    { name: "Rachin Ravindra", role: "ALL", overseas: true },
    { name: "Sam Curran", role: "ALL", overseas: true },
    { name: "Noor Ahmad", role: "BOWL", overseas: true },
    { name: "Khaleel Ahmed", role: "BOWL", overseas: false },
    { name: "Devon Conway", role: "WK", overseas: true },
    { name: "Rahul Tripathi", role: "BAT", overseas: false },
    { name: "Nathan Ellis", role: "BOWL", overseas: true },
  ],
  RCB: [
    { name: "Virat Kohli", role: "BAT", overseas: false },
    { name: "Rajat Patidar", role: "BAT", overseas: false },
    { name: "Liam Livingstone", role: "ALL", overseas: true },
    { name: "Phil Salt", role: "WK", overseas: true },
    { name: "Josh Hazlewood", role: "BOWL", overseas: true },
    { name: "Mohammed Siraj", role: "BOWL", overseas: false },
    { name: "Yash Dayal", role: "BOWL", overseas: false },
    { name: "Krunal Pandya", role: "ALL", overseas: false },
    { name: "Bhuvneshwar Kumar", role: "BOWL", overseas: false },
    { name: "Jitesh Sharma", role: "WK", overseas: false },
    { name: "Devdutt Padikkal", role: "BAT", overseas: false },
  ],
  KKR: [
    { name: "Ajinkya Rahane", role: "BAT", overseas: false },
    { name: "Andre Russell", role: "ALL", overseas: true },
    { name: "Sunil Narine", role: "ALL", overseas: true },
    { name: "Venkatesh Iyer", role: "ALL", overseas: false },
    { name: "Quinton de Kock", role: "WK", overseas: true },
    { name: "Rinku Singh", role: "BAT", overseas: false },
    { name: "Varun Chakravarthy", role: "BOWL", overseas: false },
    { name: "Mitchell Starc", role: "BOWL", overseas: true },
    { name: "Harshit Rana", role: "BOWL", overseas: false },
    { name: "Angkrish Raghuvanshi", role: "BAT", overseas: false },
    { name: "Moeen Ali", role: "ALL", overseas: true },
  ],
  DC: [
    { name: "Axar Patel", role: "ALL", overseas: false },
    { name: "Jake Fraser-McGurk", role: "BAT", overseas: true },
    { name: "Tristan Stubbs", role: "WK", overseas: true },
    { name: "KL Rahul", role: "WK", overseas: false },
    { name: "Kuldeep Yadav", role: "BOWL", overseas: false },
    { name: "Mitchell Marsh", role: "ALL", overseas: true },
    { name: "Faf du Plessis", role: "BAT", overseas: true },
    { name: "Mukesh Kumar", role: "BOWL", overseas: false },
    { name: "Ashutosh Sharma", role: "BAT", overseas: false },
    { name: "Mohit Sharma", role: "BOWL", overseas: false },
  ],
  SRH: [
    { name: "Pat Cummins", role: "BOWL", overseas: true },
    { name: "Heinrich Klaasen", role: "WK", overseas: true },
    { name: "Travis Head", role: "BAT", overseas: true },
    { name: "Abhishek Sharma", role: "ALL", overseas: false },
    { name: "Nitish Kumar Reddy", role: "ALL", overseas: false },
    { name: "Mohammed Shami", role: "BOWL", overseas: false },
    { name: "Adam Zampa", role: "BOWL", overseas: true },
    { name: "Ishan Kishan", role: "WK", overseas: false },
    { name: "Harshal Patel", role: "BOWL", overseas: false },
    { name: "Rahul Chahar", role: "BOWL", overseas: false },
  ],
  PBKS: [
    { name: "Shreyas Iyer", role: "BAT", overseas: false },
    { name: "Shashank Singh", role: "BAT", overseas: false },
    { name: "Arshdeep Singh", role: "BOWL", overseas: false },
    { name: "Yuzvendra Chahal", role: "BOWL", overseas: false },
    { name: "Marcus Stoinis", role: "ALL", overseas: true },
    { name: "Prabhsimran Singh", role: "WK", overseas: false },
    { name: "Glenn Maxwell", role: "ALL", overseas: true },
    { name: "Lockie Ferguson", role: "BOWL", overseas: true },
    { name: "Nehal Wadhera", role: "BAT", overseas: false },
    { name: "Azmatullah Omarzai", role: "ALL", overseas: true },
  ],
  RR: [
    { name: "Sanju Samson", role: "WK", overseas: false },
    { name: "Jos Buttler", role: "WK", overseas: true },
    { name: "Riyan Parag", role: "ALL", overseas: false },
    { name: "Shimron Hetmyer", role: "BAT", overseas: true },
    { name: "Dhruv Jurel", role: "WK", overseas: false },
    { name: "Yashasvi Jaiswal", role: "BAT", overseas: false },
    { name: "Jofra Archer", role: "BOWL", overseas: true },
    { name: "Wanindu Hasaranga", role: "ALL", overseas: true },
    { name: "Sandeep Sharma", role: "BOWL", overseas: false },
    { name: "Maheesh Theekshana", role: "BOWL", overseas: true },
  ],
  LSG: [
    { name: "Nicholas Pooran", role: "WK", overseas: true },
    { name: "Ravi Bishnoi", role: "BOWL", overseas: false },
    { name: "Mayank Yadav", role: "BOWL", overseas: false },
    { name: "David Miller", role: "BAT", overseas: true },
    { name: "Aiden Markram", role: "ALL", overseas: true },
    { name: "Avesh Khan", role: "BOWL", overseas: false },
    { name: "Rishabh Pant", role: "WK", overseas: false },
    { name: "Mitchell Marsh", role: "ALL", overseas: true },
    { name: "Digvesh Rathi", role: "BOWL", overseas: false },
  ],
  GT: [
    { name: "Shubman Gill", role: "BAT", overseas: false },
    { name: "Sai Sudharsan", role: "BAT", overseas: false },
    { name: "Rashid Khan", role: "ALL", overseas: true },
    { name: "Prasidh Krishna", role: "BOWL", overseas: false },
    { name: "Kagiso Rabada", role: "BOWL", overseas: true },
    { name: "Shahrukh Khan", role: "ALL", overseas: false },
    { name: "Rahul Tewatia", role: "ALL", overseas: false },
    { name: "Gerald Coetzee", role: "BOWL", overseas: true },
  ],
};

export const DEFAULT_2026_TEAMS = [
  { id: "T1", name: "Mvrcks", color: "#00C9FF", emoji: "🔵" },
  { id: "T2", name: "Sharks", color: "#FF6B35", emoji: "🦈" },
  { id: "T3", name: "MTR",    color: "#A8FF3E", emoji: "🟢" },
  { id: "T4", name: "Sixers", color: "#FFB830", emoji: "🟡" },
];

export const D5_TEAM_CONFIG = {
  Mvrcks: { color: "#00C9FF", emoji: "🔵" },
  Sharks: { color: "#FF6B35", emoji: "🦈" },
  MTR:    { color: "#A8FF3E", emoji: "🟢" },
  Sixers: { color: "#FFB830", emoji: "🟡" },
  Avngrs: { color: "#c084fc", emoji: "⚡" },
  Clash:  { color: "#f87171", emoji: "⚔️" },
};

export const MAIN_TEAMS = ["Mvrcks", "Sharks", "MTR", "Sixers"];

export const SCORING_RULES = {
  multipliers: {
    run: 5,
    wicket: 100,
    runOut: 50,
    stumping: 50,
    catch: 50,
    duck: -50,
  },
  bonuses: {
    runs30: 50,
    runs50: 150,
    runs100: 250,
    wkts2: 50,
    wkts3: 150,
    wkts5: 200,
    wkts6: 100,
    catches3: 100,
    catches5: 200,
    roStump3: 100,
    sixes5: 150,
    sixes10: 300,
    hatTrickWkts: 400,
    hatTrickSixes: 100,
    maidenOver: 200,
  },
  captainMultiplier: 2,
};
